#!/bin/bash


#    Copyright 2021 Bret Young - myinternetalert.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


##############################################################################

CHS='chs.myinternetalert.com'

while true
do
  /usr/bin/systemd-notify WATCHDOG=1

  TEMP=$(/usr/bin/getent ahosts $CHS | head -n 1 | awk '{print $1}')
  if [[ $TEMP =~ [0-9a-fA-Fa-f.] ]]  && \
     [[ ! $TEMP = "127.0.0.1" ]] && \
     [[ ! $TEMP = "::1" ]]; then
    echo $TEMP > /tmp/home
  fi



  RESPONSE=$(/usr/bin/ping -c 1 -W 2 -n -s 0 $(cat /tmp/home))
  if [[ ! $RESPONSE =~ ", 1 received, " ]] || [[ $RESPONSE =~ "unreachable" ]]; then
    SysLog  "Single ping failed"
    /usr/bin/systemd-notify WATCHDOG=1

    # flood ping 3 packets if the single ping attempts failed
    while true
    do
      RESPONSE=$(/usr/bin/ping -c 3 -f -W 2 -n -s 1 $(cat /tmp/home))
      if [[ $RESPONSE =~ "unreachable" ]] || \
         [[ $RESPONSE =~ ", 0 received, " ]] || \
         [[ ! $RESPONSE =~ [a-z0-9] ]]; then
        /usr/bin/systemd-notify WATCHDOG=1
        sleep 0.2
      else
        /usr/bin/systemd-notify WATCHDOG=1
        /usr/bin/touch /tmp/up
        break
      fi
    done
  fi

  if [[ -f /tmp/up ]]; then
    #  if connection was lost, then ISP DHCP may change external IP
    #  requires re-register so that mac & ip address are captured
    /usr/bin/systemctl restart register
  fi

  # Following four lines enable pinger to restart before an alert is issued
  /usr/bin/systemd-notify WATCHDOG=1
  /usr/bin/sleep 5 
  /usr/bin/systemd-notify WATCHDOG=1
  /usr/bin/sleep 5 

done
