#!/bin/bash

# My InterNet Alert script to deliver
# heart beat to cloud server.  


CHS='chs.myinternetalert.com'
LOG='/var/log/mina/pinger.log'


SysLog() {
  # send message to register log
  /usr/bin/echo $(date +'%Y-%m-%d %H:%M:%S') $1 >> $LOG
}

##########################################################################

SysLog "Starting pinger ..."
# Restart register to assure correlation between
# RPi mac address and external ip address
SysLog "Restarting register ..."
/usr/bin/systemctl restart register

while true
do
  BEG=`date +%s`

  /usr/bin/systemd-notify WATCHDOG=1

  # utilize ip address for ping incase resolver has issues
  TEMP=$(/usr/bin/getent ahosts $CHS | head -n 1 | awk '{print $1}')
  if [[ $TEMP =~ [0-9a-fA-Fa-f.] ]]  && \
     [[ ! $TEMP = "127.0.0.1" ]] && \
     [[ ! $TEMP = "::1" ]]; then
    echo $TEMP > /tmp/home
  fi



  RESPONSE=$(/usr/bin/ping -c 1 -W 2 -n -s 0 $(cat /tmp/home))
  if [[ ! $RESPONSE =~ ", 1 received, " ]] || [[ $RESPONSE =~ "unreachable" ]]; then
    SysLog  "Single ping failed"
    /usr/bin/systemd-notify WATCHDOG=1

    # flood ping 3 packets at a time if the single ping attempts failed
    while true
    do
      RESPONSE=$(/usr/bin/ping -c 10 -f -W 2 -n -s 1 $(cat /tmp/home))
      if [[ $RESPONSE =~ "unreachable" ]] || \
         [[ $RESPONSE =~ ", 0 received, " ]] || \
         [[ ! $RESPONSE =~ [a-z0-9] ]]; then
        /usr/bin/systemd-notify WATCHDOG=1
 	if [[ ! $(/usr/bin/tail -n 1 $LOG) =~ "Flood ping failed" ]];then 
     	  SysLog "Flood ping is failing"
        fi
	sleep 0.2
      else
        /usr/bin/systemd-notify WATCHDOG=1
        SysLog "Flood ping succeeded"
	/usr/bin/touch /tmp/up
        break
      fi
    done
  fi

  if [[ -f /tmp/up ]]; then
    #  if connection was lost, then ISP DHCP may change external IP
    #  requires re-register so that mac & ip address are captured
    /usr/bin/systemctl restart register
    SysLog "Restarted register"
  fi

  END=`date +%s`
  BAL=$(($END-$BEG ))
  if [[ $(($END-$BEG))  -gt 0 ]]; then
    SysLog "Processing time: $BAL sec"
  fi

  for IDX in $(seq 1 $((10-$END+$BEG)))
  do
    /usr/bin/systemd-notify WATCHDOG=1
    /usr/bin/sleep 1 
  done


done
