#!/bin/bash


CRT='/etc/ssl/certs/ca-certificates.crt'
MAC=$(/usr/bin/cat /sys/class/net/eth0/address | /usr/bin/sed s/://g)
CHS='https://chs.myinternetalert.com/api/reg'
LOG='/var/log/mina/register.log'


SysLog() {
  # send message to register log
  /usr/bin/echo $(date +'%Y-%m-%d %H:%M:%S') $1 >> $LOG
}


SysLog "Starting register ..."


while true
do

  UPTIME=$(cat /proc/uptime | /usr/bin/awk '{print $1}' | sed 's/\..*$//')

  RESPONSE=$(/usr/bin/curl -s --cacert "$CRT" -X POST \
             -H "x-mina: $MAC" -H "x-time: $UPTIME" "$CHS");

  if [[ $RESPONSE =~ [0-9a-zA-Z] && -f /tmp/up ]]; then
    SysLog "Removing /tmp/up"
    rm /tmp/up
  fi

  for i in $(seq 1 60)
  do
    /usr/bin/systemd-notify WATCHDOG=1
    /usr/bin/sleep 60 
  done

done
